version: "3"
name: ${project}
services:
    ${image}:
        privileged: true
        stdin_open: true
        init: true
        tty: true
        shm_size: 512m
        ports:
            - 6901:6901
        environment:
            - VNC_PW=password
#        volumes:
            # - ${PWD}:/tmp/roguesecrets
            # - /:/host_root/
 #       env_file:
 #           - /under/my
        # working_dir: /tmp/roguesecrets
        image: ${project}/${image}:${tag}
