#original https://www.programonaut.com/how-to-deploy-a-git-repository-to-a-server-using-github-actions/
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Request Pull
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
 #docker://alpine:latest
    steps:
    - name: request pull
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        wget -O- -q --header="X-Auth-Token: ${{ secrets.update_token }}" https://cab1.kqsfl.com/update > /dev/null
